version: "3.8"
services:
  inventoryservice:
    build:
     context: .
     dockerfile: Dockerfile
    image: inventoryservice
    container_name: inventoryservice
    ports:
      - "8080:8080"
    networks:
      - inventorynetwork

networks:
 inventorynetwork:
  name: inventorynetwork
  driver: bridge