version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
    networks:
      - inventorynetwork

networks:
 inventorynetwork:
  name: inventorynetwork
  driver: bridge